[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "sneep"
authors = [{name = "Nina Baumgarten", email = "n.baumgarten@em.uni-frankfurt.de"}]
dynamic = ["version", "description"]
